### ISSUE TITLE
Changing a page in GitBook is not visible in the files of the gitrepo locally

### ISSUE THREAD

**Issue by andywenk** [GitbookIO/gitbook#1183]
Hi there,

first of all thanks a lot for creating GitBook. I really can't wind my head around this thing. Here are the steps I did:
- I created a new book in GitBook
- I added pages and some text
- I was not able to see anywhere, where the repo is physically on my HD 
- After I found out where that is, I added an image. But I could not see the image in the GitBook editor. Why?
- I closed GitBook for that day
- I opened GitBook the other day. Surprise - the image is now there ...
- I thought I did a mistake so I started to edit a page.
- I opened the edited file on my HD (Finder, OS X) but I can't see the changes ...

This reads like a newbie wrote some explanation and that's per intention. I am very familar with git and understood, that GitBook is creating automatic commits, when a page is saved. But why do I not see the changes in the physical file. This is very confusing for me and I do not understand the concept.

User Stories:

"As an editor I want to change or add files (*.md, *.jpg and so on) at the physical location of the used git repository for GitBook. I want to see these changes immediately in the GitBook editor."

"As an editor I want to change or add files (*.md, *.jpg and so on) in the GitBook editor and see these changes immediately in the used git repository."

Do I miss something here? 

Thanks and all the best

Andy

**Comment by nagim** [comment]
Hi,

Whether or not GitBook Editor commits your changes automatically on saving depends on your settings. Check in the editor settings if automatic commits are enabled. If not, you have to commit manually after saving.
You can add/remove files from the editor itself. In the file tree view, right click and choose upload files or upload folders.
Guess if you copy the files to the folder outside the editor, you need to run a `git add` manually after.

Cheers,
Imre

**Comment by andywenk** [comment]
@nagim,

thanks for your answer. I am aware how to add files inside the editor. But as I described and as you mentioned in the second part of your comment, I am not able to understand, how to add files outside the editor - means directly in the repo locally.

What I am faced now is to figure out, where Gitbook is placing the files on my local HD. To circumvent all these hassles, I have created a book on gitbook.com and cloned it. Added all the stuff I need (I am at the beginning, so no problem) and pushed it. Everything is fine. BUT - where can I in GitBook where the files are locally. I have a guess, because a new directory was created (I changed the settings for GitBook). But the files there are not corresponding with what I see in the editor.

Sorry, but this is really strange. I am mostly working on the command line so if the result of what I see is different to what I expect is breaking my brain ;-)

Thanks for further hints. If this behaviour is considered a bug, I am happy to open a new issue with a consolidated description.

Cheers

Andy

**Comment by kentf** [comment]
So much this.

I sometimes use Notepad++ (or other editors). When opening the Gitbook Editor, I don't want previous work to be erased/unstaged without any warning. Even code files (cpp/hpp) are reverted!

This is very bad, and is a deal breaking "feature".

**Comment by abeolson** [comment]
Just getting started using gitbook editor and ran across this behavior. Gitbook editor has a bad UI and should be fixed. 

User story

1. If I open a local file (with any editor) and click "save", I expect that the changes are saved **to the local file**. 
1. If I want to sync to a version control repository. I click "sync", and I expect that the changes will be saved **both to the local file and the repo**.

**Comment by jluna79** [comment]
+1

This is a really annoying behaviour (bug) on a really useful and otherwise really nice tool!

**Comment by ztl8702** [comment]
+1 for this bug to be fixed.

**Comment by Spiralis** [comment]
**Are no-one working on this for the moment??** 

IMHO this is so bad that I cannot understand how it was released as a stable version. This was driving my crazy, until I found this post (and #1145). 

Like @kentf mentioned, this also seems to affect non-gitbook files. It actually just seems like it reverts to the latest commit in the repo. I cannot understand how on earth anyone thought that that was a good idea?

**Comment by kataras** [comment]
The issue still exists, I have a serious problem, I have enabled two-factor auth via github.com, when I try to sync gitbook goes at loop because it can't authenticate my github two-factor enabled account, so now I can't save the changes to the remote branch, neither to my local folder, I have stuck.

**Comment by SamyPesse** [comment]
@Spiralis I understand the frustration here.

The GitBook Editor **only works with files in the GIT history**. We are working on fixing this ( https://github.com/GitbookIO/feedback/issues/101).

**Comment by Spiralis** [comment]
Thanks @SamyPesse. I am very happy to hear that this is being addressed 😄 👍
